CREATE TABLE MOTO (
    ID BIGSERIAL PRIMARY KEY,
    PLACA VARCHAR(255) NOT NULL UNIQUE,
    MODELO VARCHAR(255) NOT NULL,
    ANO INT NOT NULL,
    RFID_TAG VARCHAR(255) NOT NULL UNIQUE,
    STATUS VARCHAR(255),
    OBSERVACOES VARCHAR(255)
);

CREATE TABLE SENSOR (
    ID BIGSERIAL PRIMARY KEY,
    CODIGO VARCHAR(255) NOT NULL UNIQUE,
    posicao_x INT NOT NULL, -- Corrigido
    posicao_y INT NOT NULL, -- Corrigido
    DESCRICAO VARCHAR(255)
);

CREATE TABLE MOVIMENTACAO (
    ID BIGSERIAL PRIMARY KEY,
    MOTO_ID BIGINT NOT NULL,
    SENSOR_ID BIGINT NOT NULL,
    DATA_HORA TIMESTAMP,
    CONSTRAINT FK_MOVIMENTACAO_MOTO FOREIGN KEY (MOTO_ID) REFERENCES MOTO(ID),
    CONSTRAINT FK_MOVIMENTACAO_SENSOR FOREIGN KEY (SENSOR_ID) REFERENCES SENSOR(ID)
);

CREATE TABLE USERS (
    ID BIGSERIAL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255) NOT NULL
);

-- Inserindo uma moto de teste inicial
INSERT INTO MOTO(PLACA, MODELO, ANO, RFID_TAG, STATUS, OBSERVACOES)
VALUES ('TST-0001', 'Honda CG Titan', 2024, 'RFID-TESTE-001', 'DISPONIVEL', 'Moto de teste');